# Generated by Django 5.1.7 on 2025-04-14 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
